// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/accommodations": {
    params: {};
  };
  "/hostings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/accommodations" | "/hostings";
  };
  "layout.tsx": {
    id: "layout";
    page: "/" | "/accommodations" | "/hostings";
  };
  "routes/customers.tsx": {
    id: "routes/customers";
    page: "/";
  };
  "routes/accommodations.tsx": {
    id: "routes/accommodations";
    page: "/accommodations";
  };
  "routes/hostings.tsx": {
    id: "routes/hostings";
    page: "/hostings";
  };
};