### Accommodation REST API Tests

@BASE_Url = http://localhost:3000
@ACCOMMODATION_ID = aba783ce-d892-4556-a91c-9617a4b76b65
@CONTENT_TYPE = application/json

### 1. Get All Accommodations
GET {{BASE_Url}}/accommodations
Content-Type: {{CONTENT_TYPE}}